import { defineEventHandler } from 'h3'

export default defineEventHandler(() => {
  const properties = [
    {
      propertyName: 'Beckos',
      cardImage: '/images/Beckos.svg',
      cardTitle: 'Property Title 1',
      cardText: 'Property description 1',
      bedRooms: 3,
      bathRooms: 2,
      cardPrice: '500,000',
      squareFeet: '2,500',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
    {
      propertyName: 'Metro',
      cardImage: '/images/MetroCard.svg',
      cardTitle: 'Property Title 2',
      cardText: 'Property description 2',
      bedRooms: 4,
      bathRooms: 3,
      cardPrice: '1,250,000',
      squareFeet: '2,100',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
    {
      propertyName: 'SeaSide',
      cardImage: '/images/SeasideCard.svg',
      cardTitle: 'Property Title 3',
      cardText: 'Property description 3',
      bedRooms: 4,
      bathRooms: 3,
      cardPrice: '750,000',
      squareFeet: '1,800',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
    {
      propertyName: 'Benarks',
      cardImage: '/images/Beckos.svg',
      cardTitle: 'Property Title 4',
      cardText: 'Property description 4',
      bedRooms: 3,
      bathRooms: 2,
      cardPrice: '500,000',
      squareFeet: '1,900',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
    {
      propertyName: 'MetroLine',
      cardImage: '/images/Beckos.svg',
      cardTitle: 'Property Title 5',
      cardText: 'Property description 5',
      bedRooms: 4,
      bathRooms: 3,
      cardPrice: '750,000',
      squareFeet: '2,660',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
    {
      propertyName: 'Seamore',
      cardImage: '/images/SeasideCard.svg',
      cardTitle: 'Property Title 6',
      cardText: 'Property description 6',
      bedRooms: 4,
      bathRooms: 3,
      cardPrice: '750,000',
      squareFeet: '2,900',
      propertyLocation: 'Malibu, California',
      propertyImages: [
        { path: '/imageGallery/seaSideOne.svg' },
        { path: '/imageGallery/seaSideTwo.svg' },
        { path: '/imageGallery/seaSideThree.svg' },
        { path: '/imageGallery/seaSideFour.svg' },
        { path: '/imageGallery/seaSideFifth.svg' },
        { path: '/imageGallery/seaSideSixt.svg' },
        { path: '/imageGallery/seaSideSeventh.svg' },
        { path: '/imageGallery/seaSideNine.svg' },
        { path: '/imageGallery/seaSideEight.svg' },
      ],
      description:
        'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
    },
  ]

  return properties
})

// const properties = [
//   {
//     propertyName: 'Beckos',
//     cardImage: '/images/Beckos.svg',
//     cardTitle: 'Property Title 1',
//     cardText: 'Property description 1',
//     bedRooms: 3,
//     bathRooms: 2,
//     cardPrice: '500,000',
//     squareFeet: '2,500',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
//   {
//     propertyName: 'Metro',
//     cardImage: '/images/MetroCard.svg',
//     cardTitle: 'Property Title 2',
//     cardText: 'Property description 2',
//     bedRooms: 4,
//     bathRooms: 3,
//     cardPrice: '1,250,000',
//     squareFeet: '2,100',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
//   {
//     propertyName: 'SeaSide',
//     cardImage: '/images/SeasideCard.svg',
//     cardTitle: 'Property Title 3',
//     cardText: 'Property description 3',
//     bedRooms: 4,
//     bathRooms: 3,
//     cardPrice: '750,000',
//     squareFeet: '1,800',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
//   {
//     propertyName: 'Benarks',
//     cardImage: '/images/Beckos.svg',
//     cardTitle: 'Property Title 4',
//     cardText: 'Property description 4',
//     bedRooms: 3,
//     bathRooms: 2,
//     cardPrice: '500,000',
//     squareFeet: '1,900',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
//   {
//     propertyName: 'MetroLine',
//     cardImage: '/images/Beckos.svg',
//     cardTitle: 'Property Title 5',
//     cardText: 'Property description 5',
//     bedRooms: 4,
//     bathRooms: 3,
//     cardPrice: '750,000',
//     squareFeet: '2,660',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
//   {
//     propertyName: 'Seamore',
//     cardImage: '/images/SeasideCard.svg',
//     cardTitle: 'Property Title 6',
//     cardText: 'Property description 6',
//     bedRooms: 4,
//     bathRooms: 3,
//     cardPrice: '750,000',
//     squareFeet: '2,900',
//     propertyLocation: 'Malibu, California',
//     description:
//       'Discover your own piece of paradise with the Seaside Serenity Villa. T With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.',
//   },
// ]
