export const reAssets = [
  {
    id: 1,
    propertyName: 'Sunset Vista',
    cardImage: '/images/SunsetVista.svg',
    cardTitle: 'Breathtaking Oceanfront Property',
    cardText: 'Enjoy panoramic ocean views in this luxurious retreat.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '1,200,000',
    squareFeet: '3,200',
    propertyLocation: 'Laguna Beach, California',
    propertyImages: [{ path: '/imageGallery/sunsetVistaOne.svg' }],
    description:
      'This stunning property offers unmatched views of the Pacific Ocean, modern architecture, and luxurious amenities.',
  },
  {
    id: 2,
    propertyName: 'Urban Oasis',
    cardImage: '/images/UrbanOasis.svg',
    cardTitle: 'Modern Downtown Apartment',
    cardText: 'A sleek, urban residence in the heart of the city.',
    bedRooms: 2,
    bathRooms: 2,
    cardPrice: '850,000',
    squareFeet: '1,800',
    propertyLocation: 'Seattle, Washington',
    propertyImages: [{ path: '/imageGallery/urbanOasisOne.svg' }],
    description:
      'Located in the vibrant city center, this modern apartment offers convenience, style, and fantastic views.',
  },
  {
    id: 3,
    propertyName: 'Mountain Escape',
    cardImage: '/images/MountainEscape.svg',
    cardTitle: 'Rustic Cabin with Mountain Views',
    cardText: 'Experience serenity in this cozy mountain retreat.',
    bedRooms: 3,
    bathRooms: 2,
    cardPrice: '450,000',
    squareFeet: '2,200',
    propertyLocation: 'Aspen, Colorado',
    propertyImages: [{ path: '/imageGallery/mountainEscapeOne.svg' }],
    description:
      'A charming cabin with rustic finishes, breathtaking mountain views, and close proximity to hiking trails.',
  },
  {
    id: 4,
    propertyName: 'Lakeside Serenity',
    cardImage: '/images/LakesideSerenity.svg',
    cardTitle: 'Peaceful Waterfront Home',
    cardText: 'A tranquil retreat on the shores of a serene lake.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '680,000',
    squareFeet: '3,000',
    propertyLocation: 'Lake Tahoe, Nevada',
    propertyImages: [{ path: '/imageGallery/lakesideSerenityOne.svg' }],
    description:
      'This lakeside property offers stunning water views, private docks, and a peaceful atmosphere.',
  },
  {
    id: 5,
    propertyName: 'City Lights',
    cardImage: '/images/CityLights.svg',
    cardTitle: 'Penthouse with Skyline Views',
    cardText: 'Luxury penthouse overlooking the city.',
    bedRooms: 3,
    bathRooms: 3,
    cardPrice: '2,500,000',
    squareFeet: '3,500',
    propertyLocation: 'New York, New York',
    propertyImages: [{ path: '/imageGallery/cityLightsOne.svg' }],
    description:
      'This elegant penthouse features floor-to-ceiling windows, a spacious layout, and breathtaking city views.',
  },
  {
    id: 6,
    propertyName: 'Garden Retreat',
    cardImage: '/images/GardenRetreat.svg',
    cardTitle: 'Charming Home with Lush Gardens',
    cardText: 'A serene property surrounded by vibrant greenery.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '520,000',
    squareFeet: '2,900',
    propertyLocation: 'Portland, Oregon',
    propertyImages: [{ path: '/imageGallery/gardenRetreatOne.svg' }],
    description:
      'This charming home offers spacious interiors, a large backyard, and beautifully landscaped gardens.',
  },
  {
    id: 7,
    propertyName: 'Coastal Paradise',
    cardImage: '/images/CoastalParadise.svg',
    cardTitle: 'Beachfront Dream Home',
    cardText: 'Live the coastal lifestyle in this stunning beachfront home.',
    bedRooms: 5,
    bathRooms: 4,
    cardPrice: '1,800,000',
    squareFeet: '4,200',
    propertyLocation: 'Santa Barbara, California',
    propertyImages: [{ path: '/imageGallery/coastalParadiseOne.svg' }],
    description:
      'Wake up to the sound of waves in this luxurious beachfront property with direct beach access.',
  },
  {
    id: 8,
    propertyName: 'Suburban Haven',
    cardImage: '/images/SuburbanHaven.svg',
    cardTitle: 'Family-Friendly Suburban Home',
    cardText: 'A spacious home in a quiet suburban neighborhood.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '430,000',
    squareFeet: '3,000',
    propertyLocation: 'Phoenix, Arizona',
    propertyImages: [{ path: '/imageGallery/suburbanHavenOne.svg' }],
    description:
      'Perfect for families, this home features a large backyard, modern kitchen, and excellent schools nearby.',
  },
  {
    id: 9,
    propertyName: 'Desert Gem',
    cardImage: '/images/DesertGem.svg',
    cardTitle: 'Modern Desert Retreat',
    cardText: 'Sleek, modern design in a picturesque desert setting.',
    bedRooms: 3,
    bathRooms: 2,
    cardPrice: '650,000',
    squareFeet: '2,400',
    propertyLocation: 'Palm Springs, California',
    propertyImages: [{ path: '/imageGallery/desertGemOne.svg' }],
    description:
      'This desert property combines modern architecture with serene desert views and luxurious amenities.',
  },
  {
    id: 10,
    propertyName: 'Harbor View',
    cardImage: '/images/HarborView.svg',
    cardTitle: 'Stunning Waterfront Condo',
    cardText: 'A luxurious condo with harbor views.',
    bedRooms: 2,
    bathRooms: 2,
    cardPrice: '900,000',
    squareFeet: '1,700',
    propertyLocation: 'Boston, Massachusetts',
    propertyImages: [{ path: '/imageGallery/harborViewOne.svg' }],
    description:
      'This stunning condo offers breathtaking harbor views, modern interiors, and proximity to downtown.',
  },
  {
    id: 11,
    propertyName: 'Maple Manor',
    cardImage: '/images/MapleManor.svg',
    cardTitle: 'Elegant Country Estate',
    cardText: 'A charming estate in the heart of the countryside.',
    bedRooms: 5,
    bathRooms: 4,
    cardPrice: '1,100,000',
    squareFeet: '4,500',
    propertyLocation: 'Nashville, Tennessee',
    propertyImages: [{ path: '/imageGallery/mapleManorOne.svg' }],
    description:
      'This sprawling estate offers privacy, stunning landscapes, and a beautiful country setting.',
  },
  {
    id: 12,
    propertyName: 'Seaside Cottage',
    cardImage: '/images/SeasideCottage.svg',
    cardTitle: 'Cozy Beachside Getaway',
    cardText: 'A quaint cottage just steps from the beach.',
    bedRooms: 2,
    bathRooms: 1,
    cardPrice: '450,000',
    squareFeet: '1,200',
    propertyLocation: 'Charleston, South Carolina',
    propertyImages: [{ path: '/imageGallery/seasideCottageOne.svg' }],
    description:
      'This cozy cottage offers a relaxing retreat with easy access to sandy beaches and ocean breezes.',
  },
  {
    id: 13,
    propertyName: 'Hilltop Haven',
    cardImage: '/images/HilltopHaven.svg',
    cardTitle: 'Modern Home with Panoramic Views',
    cardText: 'A stunning property atop a scenic hill.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '980,000',
    squareFeet: '3,800',
    propertyLocation: 'San Diego, California',
    propertyImages: [{ path: '/imageGallery/hilltopHavenOne.svg' }],
    description:
      'This modern home offers breathtaking views, spacious interiors, and top-of-the-line amenities.',
  },
  {
    id: 14,
    propertyName: 'Rustic Farmhouse',
    cardImage: '/images/RusticFarmhouse.svg',
    cardTitle: 'Charming Farmhouse with Land',
    cardText: 'A peaceful retreat with expansive grounds.',
    bedRooms: 3,
    bathRooms: 2,
    cardPrice: '620,000',
    squareFeet: '3,000',
    propertyLocation: 'Boise, Idaho',
    propertyImages: [{ path: '/imageGallery/rusticFarmhouseOne.svg' }],
    description:
      'This rustic farmhouse offers plenty of land, modern updates, and a welcoming atmosphere.',
  },
  {
    id: 15,
    propertyName: 'Bayview Residence',
    cardImage: '/images/BayviewResidence.svg',
    cardTitle: 'Luxury Condo with Bay Views',
    cardText: 'A sleek condo overlooking the bay.',
    bedRooms: 2,
    bathRooms: 2,
    cardPrice: '890,000',
    squareFeet: '1,900',
    propertyLocation: 'San Francisco, California',
    propertyImages: [{ path: '/imageGallery/bayviewResidenceOne.svg' }],
    description:
      'Enjoy bayfront living in this luxurious condo with modern amenities and breathtaking views.',
  },
  {
    id: 16,
    propertyName: 'Golden Fields',
    cardImage: '/images/GoldenFields.svg',
    cardTitle: 'Spacious Ranch Property',
    cardText: 'A stunning ranch home with endless possibilities.',
    bedRooms: 5,
    bathRooms: 4,
    cardPrice: '1,300,000',
    squareFeet: '5,200',
    propertyLocation: 'Dallas, Texas',
    propertyImages: [{ path: '/imageGallery/goldenFieldsOne.svg' }],
    description:
      'This ranch property offers spacious living, wide-open fields, and privacy for any lifestyle.',
  },
  {
    id: 17,
    propertyName: 'Skyline Tower',
    cardImage: '/images/SkylineTower.svg',
    cardTitle: 'Luxury Highrise Apartment',
    cardText: 'A modern apartment in a prestigious building.',
    bedRooms: 3,
    bathRooms: 3,
    cardPrice: '1,000,000',
    squareFeet: '2,700',
    propertyLocation: 'Chicago, Illinois',
    propertyImages: [{ path: '/imageGallery/skylineTowerOne.svg' }],
    description:
      'This highrise apartment offers stunning city views, luxury amenities, and a prime location.',
  },
  {
    id: 18,
    propertyName: 'Willow Creek',
    cardImage: '/images/WillowCreek.svg',
    cardTitle: 'Charming Home Near Nature Trails',
    cardText: 'A lovely home in a nature-friendly community.',
    bedRooms: 4,
    bathRooms: 3,
    cardPrice: '720,000',
    squareFeet: '3,100',
    propertyLocation: 'Portland, Oregon',
    propertyImages: [{ path: '/imageGallery/willowCreekOne.svg' }],
    description:
      'Surrounded by beautiful nature trails, this home offers peace, comfort, and plenty of space.',
  },
  {
    id: 19,
    propertyName: 'Desert Retreat',
    cardImage: '/images/DesertRetreat.svg',
    cardTitle: 'Private Desert Sanctuary',
    cardText: 'A hidden gem in the desert.',
    bedRooms: 3,
    bathRooms: 2,
    cardPrice: '540,000',
    squareFeet: '2,600',
    propertyLocation: 'Phoenix, Arizona',
    propertyImages: [{ path: '/imageGallery/desertRetreatOne.svg' }],
    description:
      'This secluded desert retreat offers privacy, natural beauty, and modern conveniences.',
  },
  {
    id: 20,
    propertyName: 'Riverbend',
    cardImage: '/images/Riverbend.svg',
    cardTitle: 'Peaceful Riverside Home',
    cardText: 'A serene home along a quiet riverbank.',
    bedRooms: 3,
    bathRooms: 2,
    cardPrice: '780,000',
    squareFeet: '2,900',
    propertyLocation: 'Sacramento, California',
    propertyImages: [{ path: '/imageGallery/riverbendOne.svg' }],
    description:
      'Enjoy riverside living in this beautiful home with expansive views and modern interiors.',
  },
]
