export const testProperties = [
    {
      id: 1,
      locationText:'Coastal Escapes - Where Waves Beckon',
      title: 'Seaside Serenity Villa',
      description: 'Wake up to the soothing melody of waves. This beachfront villa offers',
      image: '/properties/desk-seaside.png',
      price: '1,250,000',
    },
    {
      id: 2,
      locationText:'Urban Oasis - Life in the Heart of the City',
      title: 'Metropolitan Haven',
      description: 'Immerse yourself in the energy of the city. This modern apartment in the heart..',
      image: '/properties/desk-metro.png',
      price: '650,000',
    },
    {
      id: 3,
      locationText:"Countryside Charm - Escape to Nature's Embrace",
      title: 'Rustic Retreat Cottage',
      description: 'Find tranquility in the countryside. This charming cottage is nestled amidst rolling hills',
      image: '/properties/desk-rustic.png',
      price: '350,000',
    },
    {
      id: 4,
      locationText:'Coastal Escapes - Where Waves Beckon',
      title: 'Seaside Serenity Villa',
      description: 'Wake up to the soothing melody of waves. This beachfront villa offers',
      image: '/properties/desk-seaside.png',
      price: '1,250,000',
    },
    {
      id: 5,
      locationText:'Urban Oasis - Life in the Heart of the City',
      title: 'Metropolitan Haven',
      description: 'Immerse yourself in the energy of the city. This modern apartment in the heart..',
      image: '/properties/desk-metro.png',
      price: '650,000',
    },
    {
      id: 6,
      locationText:"Countryside Charm - Escape to Nature's Embrace",
      title: 'Rustic Retreat Cottage',
      description: 'Find tranquility in the countryside. This charming cottage is nestled amidst rolling hills',
      image: '/properties/desk-rustic.png',
      price: '350,000',
    },
    {
      id: 7,
      locationText:'Coastal Escapes - Where Waves Beckon',
      title: 'Seaside Serenity Villa',
      description: 'Wake up to the soothing melody of waves. This beachfront villa offers',
      image: '/properties/desk-seaside.png',
      price: '1,250,000',
    },
    {
      id: 8,
      locationText:'Urban Oasis - Life in the Heart of the City',
      title: 'Metropolitan Haven',
      description: 'Immerse yourself in the energy of the city. This modern apartment in the heart..',
      image: '/properties/desk-metro.png',
      price: '650,000',
    },
    {
      id: 9,
      locationText:'Urban Oasis - Life in the Heart of the City',
      title: 'Metropolitan Haven',
      description: 'Immerse yourself in the energy of the city. This modern apartment in the heart..',
      image: '/properties/desk-metro.png',
      price: '650,000',
    },
  ];